"""Imports beta 23's strings from docs/rebuild/reference/strings into the rebuild's resources.

The original texts stay as they are in the seven beta 23 languages; French is the owner's
30 September 2026 extension (docs/decisions.md). Each element is
copied verbatim, so escapes, placeholders and attributes survive. Files are regrouped by feature
(strings_<group>.xml) instead of by the old module. While a feature has no module yet, its group
lives in :ui:design; when the module is created, point its group at it in DESTINATIONS and run
this again. Re-running replaces only the files this tool writes.

    python tools/import_strings.py          # write
    python tools/import_strings.py --check  # fail if the resources differ from the reference
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "docs" / "rebuild" / "reference" / "strings"
LOCALES = ["values", "values-fi", "values-es", "values-pt", "values-de", "values-sv", "values-it", "values-fr"]

# Old module (or old file) -> default group.
MODULE_GROUP = {
    "core": "common",
    "app": "shell",
    "iptv": "settings",
    "sportmate": "sport",
}
FILE_GROUP = {
    "strings_addons.xml": "discover",
    "strings_addon_entry.xml": "discover_entry",
    "strings_trakt.xml": "trakt",
}
# (old module, key prefix) -> group, refining the defaults above.
PREFIX_GROUP = {
    ("app", "home"): "home", ("app", "search"): "home",
    ("app", "reminder"): "live", ("app", "reminders"): "live",
    ("app", "about"): "settings", ("app", "backup"): "settings",
    ("app", "catalogue"): "vod",
    **{("iptv", p): "live" for p in ["guide", "channels", "channel", "dial", "category", "reminders"]},
    **{("iptv", p): "player" for p in ["player", "playback", "subtitle", "picture", "remote"]},
    **{("iptv", p): "sources" for p in ["source", "phone", "health", "auto", "refresh", "no", "maintenance"]},
    **{("iptv", p): "vod" for p in ["catalogue", "series", "movie", "details", "metadata", "genre", "copy",
                                    "artwork", "custom", "translate"]},
    ("iptv", "manager"): "library",
    **{(m, "action"): "common" for m in ["app", "iptv", "sportmate"]},
    **{("iptv", p): "sport" for p in ["sports", "match"]},
}
# Groups whose drafts deliberately fall back to English (reference/README.md).
ENGLISH_FALLBACK_GROUPS = {"trakt", "discover_entry"}
# Lint checks newer than beta 23 that flag its texts, not mistakes (docs/decisions.md):
# MissingQuantity: es/pt/it plurals have no "many"; Android falls back to "other", as beta 23 did.
# PluralsCandidate: English "%d things" strings; converting them is feature work with translations.
# Typos: German "Pos1" is the name of the Home key.
LOCALE_IGNORES = {
    "values": ["PluralsCandidate"],
    "values-es": ["MissingQuantity"],
    "values-pt": ["MissingQuantity"],
    "values-it": ["MissingQuantity"],
    "values-de": ["Typos"],
}
# Where each group is written. Every group sits in :ui:design until its feature module exists.
DESTINATIONS: dict[str, Path] = defaultdict(lambda: ROOT / "ui" / "design" / "src" / "main" / "res")

ELEMENT = re.compile(
    r'<(string|plurals|string-array)\b[^>]*?\bname="([^"]+)"[^>]*?(?:/>|>.*?</\1>)',
    re.S,
)
HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/import_strings.py from docs/rebuild/reference/strings. Edit the texts there. -->\n'


def group_of(module: str, file_name: str, key: str) -> str:
    if file_name in FILE_GROUP:
        return FILE_GROUP[file_name]
    prefix = key.split("_", 1)[0]
    return PREFIX_GROUP.get((module, prefix), MODULE_GROUP[module])


def collect() -> dict[tuple[str, str], dict[str, str]]:
    """(group, locale) -> key -> verbatim element text."""
    out: dict[tuple[str, str], dict[str, str]] = defaultdict(dict)
    owner: dict[tuple[str, str], str] = {}  # (locale, key) -> group: one module must not define a key twice
    for module in MODULE_GROUP:
        for locale in LOCALES:
            folder = REFERENCE / module / locale
            if not folder.is_dir():
                continue
            for path in sorted(folder.glob("*.xml")):
                for match in ELEMENT.finditer(path.read_text(encoding="utf-8")):
                    key, element = match.group(2), match.group(0)
                    group = group_of(module, path.name, key)
                    if owner.setdefault((locale, key), group) != group:
                        sys.exit(f"{key} would be defined in two groups ({owner[(locale, key)]}, {group}); map its prefix")
                    bucket = out[(group, locale)]
                    if key in bucket and bucket[key] != element:
                        sys.exit(f"{key} has different texts in two old modules ({locale}); rename one")
                    bucket[key] = element
    return out


def render(group: str, locale: str, elements: dict[str, str]) -> str:
    attrs = ' xmlns:tools="http://schemas.android.com/tools"'
    ignores = list(LOCALE_IGNORES.get(locale, []))
    if group in ENGLISH_FALLBACK_GROUPS:
        ignores.append("MissingTranslation")
    if ignores:
        attrs += f' tools:ignore="{",".join(ignores)}"'
    body = "\n".join(f"    {elements[k]}" for k in elements)
    return f"{HEADER}<resources{attrs}>\n{body}\n</resources>\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    wanted: dict[Path, str] = {}
    for (group, locale), elements in collect().items():
        wanted[DESTINATIONS[group] / locale / f"strings_{group}.xml"] = render(group, locale, elements)

    stale = []
    for path, text in sorted(wanted.items()):
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        sys.exit("Strings differ from the reference:\n" + "\n".join(str(p.relative_to(ROOT)) for p in stale))
    keys = len({k for (g, loc), e in collect().items() if loc == "values" for k in e})
    print(f"{len(wanted)} files, {keys} English keys, {len(stale)} {'stale' if args.check else 'written'}")


if __name__ == "__main__":
    main()
